---
name: install tfdir
description: install tfdir

inputs:
  token:
    required: true
    description: token

runs:
  using: composite
  steps:
    - name: install tfdir
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        curl "https://$GITHUB_TOKEN@raw.githubusercontent.com/torana-us/tfdir/master/installer.sh" | bash
