---
name: install tfdir
description: install tfdir

inputs:
  token:
    required: true
    description: token

runs:
  using: composite
  steps:
    - name: install tfdir
      shell: bash
      run: |
        curl "https://${{ inputs.token }}@raw.githubusercontent.com/torana-us/tfdir/master/installer.sh" | bash
