---
name: install tfdir
description: install tfdir

inputs:
  token:
    required: true
    description: token

runs:
  using: composite
  steps:
    - name: install tfdir
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh api -H "accept: application/vnd.github.v3.raw" /repos/torana-us/tfdir/contents/installer.sh | bash
        mv ./tfdir /usr/local/bin/
