---
name: install tfdir
description: install tfdir

runs:
  using: composite
  steps:
    - id: get_token
      uses: torana-us/sre-shared-actions/.github/actions/get_token@master
      with:
        app_id: 350245
        private_key: ${{ secrets.TORANA_READ_REPO_PRIVATE_KEY }}
    - name: install tfdir
      shell: bash
      run: |
        curl "https://${{ steps.get_token.outputs.token }}@raw.githubusercontent.com/torana-us/tfdir/master/installer.sh" | bash
