---
name: install tfdir
description: install tfdir

inputs:
  token:
    required: true
    description: token
  branch:
    required: false
    default: master
    description: branch

runs:
  using: composite
  steps:
    - name: install tfdir
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        /home/runner/work/_actions/torana-us/tfdir/${{ inputs.branch }}/installer.sh
        mv ./tfdir /usr/local/bin/
