---
name: install tfdir
description: install tfdir

inputs:
  token:
    required: true
    description: token

runs:
  using: composite
  steps:
    - name: install tfdir
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        ls /home/runner/work/_actions/torana-us/tfdir/test/installer
        ./installer.sh
        mv ./tfdir /usr/local/bin/
