---
name: Run linters

on:
  pull_request:

jobs:
  path-filter:
    # Get changed files to filter jobs
    outputs:
      markdownlint: ${{ steps.changes.outputs.markdownlint_any_changed == 'true' }}
      shellchecker: ${{ steps.changes.outputs.shellchecker_any_changed == 'true' }}
      ghalint: ${{ steps.changes.outputs.ghalint_any_changed == 'true' }}
      taplo: ${{ steps.changes.outputs.taplo_any_changed == 'true' }}
      yamllint: ${{ steps.changes.outputs.yamllint_any_changed == 'true' }}
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'renovate[bot]' }}
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    steps:
      - uses: tj-actions/changed-files@v40
        id: changes
        with:
          files_yaml: |
            markdownlint:
              - '{doc,docs}/*.md'
              - 'README.md'
            shellchecker:
              - '{scripts,script}/*.{bash,sh}'
              - 'bin/*.{bash,sh}'
            ghalint:
              - '.github/workflows/*.{yaml,yml}'
            taplo:
              - '*.toml'
            yamllint:
              - '.github/workflows/*.{yaml,yml}'
              - '*.{yaml,yml}'

  markdownlint:
    needs: path-filter
    if: needs.path-filter.outputs.markdownlint == 'true'
    uses: torana-us/torana-shared-actions/.github/workflows/wc-markdownlint.yml@master
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  shellchecker:
    needs: path-filter
    if: needs.path-filter.outputs.shellchecker == 'true'
    uses: torana-us/torana-shared-actions/.github/workflows/wc-shellchecker.yml@master
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  ghalint:
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    uses: torana-us/torana-shared-actions/.github/workflows/wc-ghalint.yml@master
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  yamllint:
    needs: path-filter
    if: needs.path-filter.outputs.yamllint == 'true'
    uses: torana-us/torana-shared-actions/.github/workflows/wc-yamllint.yml@master
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  taplo:
    needs: path-filter
    if: needs.path-filter.outputs.taplo == 'true'
    uses: torana-us/torana-shared-actions/.github/workflows/wc-taplo.yml@master
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  gitleaks:
    uses: torana-us/torana-shared-actions/.github/workflows/wc-gitleaks.yml@master
    if: ${{ github.actor != 'renovate[bot]' }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  typos:
    uses: torana-us/torana-shared-actions/.github/workflows/wc-typos.yml@master
    if: ${{ github.actor != 'renovate[bot]' }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
