---
name: Run shell checker

on: workflow_call

jobs:
  sh_checker:
    name: Run sh-checker
    runs-on: ubuntu-latest
    timeout-minutes: 8
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Comment remove PR
        timeout-minutes: 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -xv
          # shellcheck disable=SC2016
          remove_comment_ids=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
            --jq '.[] | select(.user.login == "github-actions[bot]") | select(.body | startswith("#### `sh-checker report`\n\n")) | .id')

          if [ -n "$remove_comment_ids" ]; then
            for comment_id in $remove_comment_ids; do
              gh api \
                --method DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "repos/${{ github.repository }}/issues/comments/$comment_id"
            done
          fi
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Run sh-checker
        timeout-minutes: 5
        uses: luizm/action-sh-checker@17bd25a6ee188d2b91f677060038f4ba37ba14b2 # v0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -s
        with:
          sh_checker_comment: true
